{% set name = "pcdsdevices" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/pcdsdevices/archive/v{{ version }}.tar.gz
  sha256: ec4d9b7ad7fb37bf62048eae653b9b833883105f3bd664ac495d0f99bd06ddc1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - bluesky >=1.6.4
    - happi
    - jsonschema
    - matplotlib-base
    - numpy
    - ophyd >=1.5.1
    - pcdscalc >=0.2.0
    - pcdsutils >=0.4.0
    - pint
    - prettytable
    - pyepics >=3.4.2
    - pytmc >=2.7.0
    - pyyaml
    - schema
    - scipy
  run_constrained:
    - lightpath >=1.0.0
    - pmgr >=2.0.2

test:
  imports:
    - pcdsdevices

about:
  home: https://github.com/pcdshub/pcdsdevices
  doc_url: https://pcdshub.github.io/pcdsdevices/
  dev_url: https://github.com/pcdshub/pcdsdevices
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: Collection of Ophyd device subclasses for IOCs unique to the Linac Coherent Light Source (LCLS) at SLAC

extra:
  recipe-maintainers:
    - klauer
    - zrylettc
    - zllentz
