{% set name = "pcdsdevices" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/pcdsdevices/archive/v{{ version }}.tar.gz
  sha256: 95b9c98683d15d1b39f1fe02f6d97e66ae52c7ccf683c19c7a73743f8eabfabb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bluesky >=1.5.0
    - happi
    - jsonschema
    - matplotlib-base
    - numpy
    - ophyd >=1.5.1
    - pcdscalc >=0.2.0
    - pcdsutils >=0.4.0
    - pint
    - prettytable
    - pyepics
    - pytmc >=2.6.0
    - pyyaml
    - schema
    - scipy

test:
  imports:
    - pcdsdevices

about:
  home: https://github.com/pcdshub/pcdsdevices
  doc_url: https://pcdshub.github.io/pcdsdevices/
  dev_url: https://github.com/pcdshub/pcdsdevices
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: Collection of Ophyd device subclasses for IOCs unique to the Linac Coherent Light Source (LCLS) at SLAC

extra:
  recipe-maintainers:
    - klauer
    - hhslepicka
    - zllentz
